version: '3.8'

services:
  myride-tracker:
    image: ghcr.io/enkeboll/myride-tracker:latest
    container_name: myride-tracker
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
